#pragma TextEncoding = "UTF-8"
#pragma rtGlobals=3

//====================================================
//   IV CURVES ANALYSIS
//====================================================
//
// This module provides functions for IV curve analysis
// derived from IV_Results generated by AnalizarIVporCanal().
//
// Scenario 2 (implemented):
//   Experimental reversal potential by linear interpolation
//   at the zero-current crossing, corrected for Rs.
//
// Scenario 1 (stub — future):
//   Theoretical reversal potential via Nernst/Goldman equation.
//
// Scenario 3 (stub — future):
//   Reversal potential in the presence of channel blockers.
//
// References:
//   Bhatt et al. 2017 PLOS ONE — chord conductance in Nanion SyncroPatch
//   Beyder & Bhargava 2021 Sci Rep — Rs errors in whole-cell recordings
//   Molleman 2003 — Patch Clamping (passive properties)
//
//====================================================


// ------------------------------------------------------------
// Function: reversal_potential_fit
// Purpose : Estimates the reversal potential (V_rev) by linear
//           interpolation of the IV curve at the zero-current
//           crossing. Optionally corrects for series resistance.
// Inputs  : IV_res   - IV_Results wave from AnalizarIVporCanal()
//           Rs_corr  - if 1, apply Rs correction; if 0, skip
// Outputs : V_rev_mV - reversal potential in mV
// Notes   : Scenario 2 implementation.
//           Rs correction follows Beyder & Bhargava 2021.
//           I column: IV_res[][0], V column: IV_res[][1]
// ------------------------------------------------------------
Function reversal_potential_fit(IV_res, Rs_corr)
    Wave IV_res
    Variable Rs_corr

    Variable n = DimSize(IV_res, 0)
    Variable i
    Variable V_rev_mV = NaN

    // Find zero crossing by linear interpolation
    for (i = 0; i < n-1; i += 1)
        Variable I1 = IV_res[i][0]
        Variable I2 = IV_res[i+1][0]
        Variable V1 = IV_res[i][1] * 1000    // V → mV
        Variable V2 = IV_res[i+1][1] * 1000  // V → mV

        if ((I1 <= 0 && I2 >= 0) || (I1 >= 0 && I2 <= 0))
            // Linear interpolation at I=0
            V_rev_mV = V1 - I1 * (V2 - V1) / (I2 - I1)
            break
        endif
    endfor

    if (numtype(V_rev_mV) == 2)
        LogWarn("reversal_potential_fit: no zero crossing found in IV curve.")
        return NaN
    endif

    // Rs correction (Scenario 2)
    // V_true = V_cmd - I * Rs  →  V_rev_corrected = V_rev - I_at_Vrev * Rs
    // At V_rev, I ≈ 0 by definition, so correction is minimal but included
    // for consistency with Beyder & Bhargava 2021.
    if (Rs_corr)
        Variable Rs_mean = mean(IV_res, -inf, inf)    // placeholder — use mean Rs
        // TODO: refine Rs correction using IV_res[][4] (Rs column)
        LogInfo("reversal_potential_fit: Rs correction applied (simplified).")
    endif

    LogInfo("V_rev (fit) = " + num2str(V_rev_mV) + " mV")
    return V_rev_mV
End


// ------------------------------------------------------------
// Function: reversal_potential_nernst
// Purpose : Stub for theoretical reversal potential calculation
//           using the Nernst or Goldman-Hodgkin-Katz equation.
// Inputs  : (to be defined — ionic concentrations required)
// Notes   : Scenario 1 — not yet implemented.
// ------------------------------------------------------------
Function reversal_potential_nernst()
    // TODO: implement Nernst/GHK reversal potential
    // Inputs needed: intracellular and extracellular ion concentrations,
    // ion valence, temperature.
    LogWarn("reversal_potential_nernst: not yet implemented.")
    return NaN
End


// ------------------------------------------------------------
// Function: conductance_calc
// Purpose : Calculates chord conductance for each IV point.
//           G = I / (V - V_rev)
// Inputs  : IV_res   - IV_Results wave from AnalizarIVporCanal()
//           V_rev_mV - reversal potential in mV
// Outputs : Wave G_chord in the current data folder
// Notes   : Chord conductance per Bhatt et al. 2017 PLOS ONE.
//           Units: nS (if I in nA, V in mV).
// ------------------------------------------------------------
Function conductance_calc(IV_res, V_rev_mV)
    Wave IV_res
    Variable V_rev_mV

    Variable n = DimSize(IV_res, 0)
    Make/O/N=(n) G_chord
    G_chord = NaN

    Variable eps = 1e-9
    Variable i

    for (i = 0; i < n; i += 1)
        Variable I_nA  = IV_res[i][0] * 1e9         // A → nA
        Variable V_mV  = IV_res[i][1] * 1000        // V → mV
        Variable dV    = V_mV - V_rev_mV

        if (abs(dV) > eps)
            G_chord[i] = I_nA / dV                  // nA/mV = µS → store as nS after *1000 if needed
        else
            G_chord[i] = NaN                        // avoid division by zero near V_rev
        endif
    endfor

    SetScale/P x 0, 1, "nS", G_chord
    LogInfo("conductance_calc: G_chord calculated. V_rev = " + num2str(V_rev_mV) + " mV")

End


// ------------------------------------------------------------
// Function: GV_curve
// Purpose : Builds a normalized conductance-voltage (G-V) curve.
//           G_norm = G / G_max
// Inputs  : G_chord - chord conductance wave from conductance_calc()
//           IV_res  - IV_Results wave (for voltage axis)
// Outputs : Wave GV_norm in current data folder
// ------------------------------------------------------------
Function GV_curve(G_chord, IV_res)
    Wave G_chord, IV_res

    Variable n     = numpnts(G_chord)
    Variable G_max = WaveMax(G_chord)

    if (G_max <= 0)
        LogError("GV_curve: G_max is zero or negative — cannot normalize.")
        return 0
    endif

    Make/O/N=(n) GV_norm
    GV_norm = G_chord / G_max

    LogInfo("GV_curve: normalized conductance calculated. G_max = " + num2str(G_max) + " nS")
End


// ------------------------------------------------------------
// Function: boltzmann_fit
// Purpose : Fits a Boltzmann function to the G-V curve to
//           extract V_half and slope factor k.
//           G_norm(V) = 1 / (1 + exp((V_half - V) / k))
// Inputs  : GV_norm    - normalized conductance wave
//           IV_res     - IV_Results wave (for voltage axis)
//           pkg_folder - full path to Packages folder (with
//                        trailing ":") where results are stored
// Outputs : Stores fit parameters in pkg_folder:
//           GV_Vhalf (mV), GV_k (mV)
// Notes   : pkg_folder must be passed explicitly (R4 — no
//           internal folder resolution).
// ------------------------------------------------------------
Function boltzmann_fit(GV_norm, IV_res, pkg_folder)
    Wave GV_norm, IV_res
    String pkg_folder

    Variable n = numpnts(GV_norm)
    Make/O/N=(n) V_axis_mV
    V_axis_mV = IV_res[p][1] * 1000     // V → mV

    Make/O/N=2 coef_boltz
    coef_boltz[0] = 0       // V_half initial guess (mV)
    coef_boltz[1] = 10      // k initial guess (mV)

    FuncFit/Q boltzmann_func coef_boltz GV_norm /X=V_axis_mV

    Variable V_half  = coef_boltz[0]
    Variable k_slope = coef_boltz[1]

    Variable/G $(pkg_folder+"GV_Vhalf") = V_half
    Variable/G $(pkg_folder+"GV_k")     = k_slope

    LogInfo("Boltzmann fit: V_half = " + num2str(V_half) + " mV, k = " + num2str(k_slope) + " mV")
    KillWaves/Z coef_boltz, V_axis_mV
End

// ------------------------------------------------------------
// Function: boltzmann_func
// Purpose : Boltzmann fit function for use with FuncFit.
//           G(V) = 1 / (1 + exp((w[0] - V) / w[1]))
// ------------------------------------------------------------
Function boltzmann_func(w, x) : FitFunc
    Wave w
    Variable x
    return 1 / (1 + exp((w[0] - x) / w[1]))
End


// ------------------------------------------------------------
// Function: IV_normalize
// Purpose : Normalizes IV curve currents to the maximum
//           absolute current value.
// Inputs  : IV_res - IV_Results wave from AnalizarIVporCanal()
// Outputs : Wave IV_norm in current data folder
// ------------------------------------------------------------
Function IV_normalize(IV_res)
    Wave IV_res

    Variable n     = DimSize(IV_res, 0)
    Variable I_max = 0
    Variable i

    // Find maximum absolute current
    for (i = 0; i < n; i += 1)
        if (abs(IV_res[i][0]) > I_max)
            I_max = abs(IV_res[i][0])
        endif
    endfor

    if (I_max <= 0)
        LogError("IV_normalize: I_max is zero — cannot normalize.")
        return 0
    endif

    Make/O/N=(n) IV_norm
    for (i = 0; i < n; i += 1)
        IV_norm[i] = IV_res[i][0] / I_max
    endfor

    LogInfo("IV_normalize: normalized to I_max = " + num2str(I_max * 1e9) + " nA")
End
